"""empty message

Revision ID: fd8a877ce261
Revises: 
Create Date: 2023-02-15 00:48:50.872043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd8a877ce261'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Creators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=True),
    sa.Column('last_name', sa.String(length=120), nullable=True),
    sa.Column('nick_name', sa.String(length=120), nullable=True),
    sa.Column('url_picture', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('topics', sa.String(length=120), nullable=True),
    sa.Column('instagram', sa.String(length=120), nullable=True),
    sa.Column('tik_tok', sa.String(length=120), nullable=True),
    sa.Column('facebook', sa.String(length=120), nullable=True),
    sa.Column('twitter', sa.String(length=120), nullable=True),
    sa.Column('youtube', sa.String(length=120), nullable=True),
    sa.Column('total_followers', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Publishers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('website', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('url_logo', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Campaings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('last_date', sa.DateTime(), nullable=True),
    sa.Column('budget', sa.Integer(), nullable=True),
    sa.Column('sources', sa.String(length=250), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id_creator', sa.Integer(), nullable=False),
    sa.Column('id_publisher', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_creator'], ['Creators.id'], ),
    sa.ForeignKeyConstraint(['id_publisher'], ['Publishers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Campaings')
    op.drop_table('Publishers')
    op.drop_table('Creators')
    # ### end Alembic commands ###
